

# 头像
avatar:
  img: /img/avatar.png
  effect: true # 頭像會一直轉圈



# 菜单
menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  清单||fa fa-heartbeat:
    音乐: /music/ || fas fa-music
    照片: /Gallery/ || fas fa-images
    电影: /movies/ || fas fa-video
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart

highlight_theme: light
highlight_copy: true
highlight_shrink: true
code_word_wrap: false
highlight_height_limit: false # unit: px



# social settings (社交圖標設置)
# formal:
#   icon: link || the description
#social:
#  fab fa-github: https://github.com/xxxxx || Github
#  fas fa-envelope: mailto:xxxxxx@gmail.com || Email


#顶部图
disable_top_img: true
#index_img:
#default_top_img:
#archive_img:
#tag_img:
#tag_per_img:
#category_img:
#category_per_img:



#文章封面

cover:
  # 是否顯示文章封面
  index_enable: true
  aside_enable: true
  archives_enable: true
  # 封面顯示的位置
  # 三個值可配置 left , right , both
  position: both
  # 當沒有設置cover時，默認的封面顯示
  default_cover: 
# Replace Broken Images (替換無法顯示的圖片)
error_img:
  flink: /img/friend_404.gif
  post_page: /img/404.jpg

post_meta:
  page: # Home Page
    date_type: created # created or updated or both 主頁文章日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 主頁是否顯示分類
    tags: false # true or false 主頁是否顯示標籤
    label: true # true or false 顯示描述性文字
  post:
    date_type: both # created or updated or both 文章頁日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 文章頁是否顯示分類
    tags: true # true or false 文章頁是否顯示標籤
    label: true # true or false 顯示描述性文字

# wordcount (字數統計)
wordcount:
  enable: false
  post_wordcount: true
  min2read: true
  total_wordcount: true

# Display the article introduction on homepage
# 1: description
# 2: both (if the description exists, it will show description, or show the auto_excerpt)
# 3: auto_excerpt (default)
# false: do not show the article introduction
index_post_content:
  method: 3
  length: 500 # if you set method to 2 or 3, the length need to config

# 文章版權和許可協議
post_copyright:
  enable: true
  decode: false
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  copyright_author: David Liu
  copyright_author_href: http://localhost:4000
  copyright_url: http://localhost:4000
  copyright_info: 此文章版权归 David Liu 所有，如有转载，请注明原作者


reward:
  enable: true
  QR_code:
    - img: /img/wechat.jpg
      link:
      text: 微信
    - img: /img/alipay.jpg
      link:
      text: 支付宝

toc:
  post: true
  page: false
  number: true
  expand: falseW
  style_simple: false # for post
  
# Post edit
# Easily browse and edit blog source code online.
post_edit:
  enable: false
  # url: https://github.com/user-name/repo-name/edit/branch-name/subdirectory-name/
  # For example: https://github.com/jerryc127/butterfly.js.org/edit/main/source/
  url:
  
# 相关文章
related_post:
  enable: true
  limit: 6 # 顯示推薦文章數目
  date_type: created # or created or updated 文章日期顯示創建日或者更新日

anchor: true


post_pagination: false
photofigcaption: true
fancybox: true
# 复制相关配置
copy:
  enable: true
  copyright:
    enable: true
    limit_count: 50

footer:
  owner:
    enable: true
    since: 2021
  custom_text: Hi, welcome to my <a href="https://butterfly.js.org/">blog</a>!



translate:
  enable: true
  # 默認按鈕顯示文字(網站是簡體，應設置為'default: 繁')
  default: 繁
  #網站默認語言，1: 繁體中文, 2: 簡體中文
  defaultEncoding: 2
  #延遲時間,若不在前, 要設定延遲翻譯時間, 如100表示100ms,默認為0
  translateDelay: 0
  #當文字是簡體時，按鈕顯示的文字
  msgToTraditionalChinese: "繁"
  #當文字是繁體時，按鈕顯示的文字
  msgToSimplifiedChinese: "簡"


darkmode:
  enable: true
  # dark mode和 light mode切換按鈕
  button: true
  autoChangeMode: false

readmode: true

change_font_size: true

mermaid:
  enable: true
  # built-in themes: default/forest/dark/neutral
  theme: neutral

# aside:
#   enable: true
#   hide: false
#   button: true
#   mobile: true # 手機頁面（ 顯示寬度 < 768px ）是否顯示aside內容
#   position: right # left or right
#   card_author:
#     enable: true
#     description:
#     button:
#       enable: true
#     icon: fab fa-github
#       text: Github
#       link: https://github.com/jerryc127/hexo-theme-butterfly
#   card_announcement:
#     enable: true
#     content: This is my Blog
#   card_recent_post:
#     enable: true
#     limit: 5 # if set 0 will show all
#     sort: date # date or updated
#   card_categories:
#     enable: true
#     limit: 8 # if set 0 will show all
#     expand: none # none/true/false
#   card_tags:
#     enable: true
#     limit: 40 # if set 0 will show all
#     color: false
#   card_archives:
#     enable: true
#     type: monthly # yearly or monthly
#     format: MMMM YYYY # eg: YYYY年MM月
#     order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
#     limit: 8 # if set 0 will show all
#   card_webinfo:
#     enable: true
#     post_count: true
#     last_push_date: true
# 访问人数
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# 运行时间
runtimeshow:
  enable: true
  publish_date: 6/7/2018 00:00:00  
  ##網頁開通時間
  #格式: 月/日/年 時間
  #也可以寫成 年/月/日 時間

newest_comments:
  enable: false
  sort_order: # Don't modify the setting unless you know how it works
  limit: 6
  storage: 10 # unit: mins, save data to localStorage
  avatar: true

canvas_nest:
  enable: true
  color: '0,0,255' #color of lines, default: '0,0,0'; RGB values: (R,G,B).(note: use ',' to separate.)
  opacity: 0.7 # the opacity of line (0~1), default: 0.5.
  zIndex: -1 # z-index property of the background, default: -1.
  count: 99 # the number of lines, default: 99.
  mobile: false # false 手機端不顯示 true 手機端顯示



# A simple 404 page
error_404:
  enable: true
  subtitle: "页面没有找到"
  background: 